server:
  port: 8085
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: c##planetime
    url: jdbc:oracle:thin:@localhost:1521:XE
  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google ? ??? ???? ??.
            client-id: 778978787532-e6irljoj6d8787dnb2bsos4m1njimaj0.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 221820854194171
            client-secret: c4e5f8a95b073cf970cf325e564bb630
            scope:
              - email
              - public_profile
          # ???? OAuth2.0 ?? ????? ???? provider ??? ????.
          # ????? ???, ?? ???? ??? ????.
          kakao:
            client-id: 5160c7392d899d15696c86753370747a
            client-secret: cddyj0xFPx4to987psRfzlAQmMFjVmKH
            redirect-uri: "http://localhost:8085/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email #동의 항목
            client-name: Kakao
          naver:
            client-id: T8JIvlQD2I2WW43y2dVo
            client-secret: AL5GSoMPZK
            scope:
              - name
              - email
              - profile_image
            client-name: Naver # ????? ??? ?? ????? ???? ?????.
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8085/login/oauth2/code/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json 으로 response 하여 받음

