//server:
  servlet:
    session:
      timeout: 600s

server:
  port: '8082'

#spring:
#  jpa:
#    generate-ddl: 'true'
#    database: oracle
#    hibernate:
#      ddl-auto: create
#    show-sql: 'true'
#    database-platform: org.hibernate.dialect.Oracle10gDialect
#  thymeleaf:
#    cache: 'false'
#  datasource:
#    password: tiger
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    username: c##planetime
#    url: jdbc:oracle:thin:@localhost:1521:XE
#  devtools:
#    livereload:
#      enabled: 'true'
#logging:
#  level:
#    org:
#      hibernate: info
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      dialect:
        org.hibernate.dialect.Oracle10gDialect


handlebars:
  suffix: .html
  expose-session-attributes: true